baseurl = "https://jdheyburn.co.uk/"
title = "JDHeyburn"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

googleAnalytics = "UA-139246187-1"

lastmod = [":fileModTime", ":default"]

enableEmoji = true

[params]
    author = "Joseph D. Heyburn"
    description = "Ramblings of a tech guy"
    keywords = "blog,developer,devops,cloud"
    info = "Software / DevOps / Cloud Engineer"
    avatarurl = "images/me.jpg"
    footercontent = ""
    toc = true
    images = ["images/jdheyburn_co_uk_card.png"]

    dateformat = "2 January 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"
    
    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/jdheyburn/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/jdheyburn/"
[[params.social]]
    name = "DEV.to"
    icon = "fab fa-dev"
    weight = 4
    url = "https://dev.to/jdheyburn"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 5
    url = "https://www.linkedin.com/in/jdheyburn/"
# [[params.social]]
#     name = "Medium"
#     icon = "fab fa-medium"
#     weight = 5
#     url = "https://medium.com/@johndoe"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "https://jdheyburn.co.uk/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        respectDoNotTrack = true


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/blog/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 5
        url = "/contact/"

